apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: helloworld
  type: NodePort # LoadBalancer | NodePort